version: '3.8' 
 
services: 
 
  web: 
    build: . 
    container_name: travel-guide-web 
    ports: 
      - "5000:5000" 
    environment: 
      - FLASK_ENV=development 
      - MYSQL_HOST=db 
      - MYSQL_USER=root 
      - MYSQL_PASSWORD=root_password 
      - MYSQL_DB=travel_guide 
    depends_on: 
      - db 
    volumes: 
      - .:/app 
 
  db: 
    image: mysql:5.7 
    container_name: travel-guide-db 
    environment: 
      MYSQL_ROOT_PASSWORD: root_password 
      MYSQL_DATABASE: travel_guide 
    ports: 
      - "3308:3306" 
    volumes: 
      - mysql_data:/var/lib/mysql 
 
volumes: 
  mysql_data: 
    driver: local 
